name: Build on commit
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build sources
        run: cd kotlin; ./gradlew build